#
# Makefile --Build rules for SKEL, the skeleton file processor.
#
language = sh nroff

SH_SRC = skeleton-midden.sh skeleton.sh
MAN1_SRC = skeleton.1

include makeshift.mk 

install: install-all
uninstall: uninstall-all
