#
# Makefile --Rules for building skeleton's library code.
#
language = c

H_SRC = skeleton.h
C_SRC = skeleton.c version.c

include makeshift.mk library.mk

#install: install-all
#uninstall: uninstall-all
